language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: sh run_travis.sh
deploy:
  provider: heroku
  api_key:
    secure: EjlxGH2UrcKw5v8DXAfZ71ERpZuEIBfmkmFsCnAjGKNr0EZhuJaxoSMsEW/7p79TPBgj47QtxwX4si2SsZCmGxbL4toi1fv+w4twNBIrKwPaz6u9n7ynH0liGyxBrUHDcD1qm2LxNnTXMh07AVL1IZuvq3fM6ekGSljSXDUfoEDv1bI6lJFYP7lhTEgcKHbzlA1SrrezNNiN+jCWJ/+0S1D5KMPgxPRcm++OvdT9opRQHMGwLThWoLBoMl9YtR61Dk3Ow5tzRwWu3jqz9iKTtho8mvAmraClZoyEcEGGy0z80vCrG6UkUbHMh3NPKabpc4XVMEw5QRBq09YtaI9gwPyw6hxpozzKvh8kVvQ2o8YK9FxpSh30GIRNbVMP0N70j5QFGORT1zbkjdvgnanil+MPc4SUhOhsI9r5dLnOzYf60JwZHQ6WpI9jXHClWAdEVDVr7f07Eu1N4R7egoAzgPtZkDIfDmcC7JzkmZ909GZwnZWUy5dXkxU7btO+QhAUBc7P40FRsvMN+XQsjkDKX4tIhhV7Fh8TS8S30EDqH7MlTvh8IRJog5ypSKYu53oeYgATF8ayYdL6aoXm1r1gyEHYEqeR5BZcebVcDdYdVDsFzXAle1FjtlfMFZHmCv/sSQuuGQ1XagwSGTAaX0NtNskRbAIH2meojhaZVM8IHNg=
  app: britecore-featurerequests
  on:
    repo: ammoti/FeatureRequest
